spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartiv_dev
    username: ${DB_USERNAME:smartiv}
    password: ${DB_PASSWORD:smartiv}
  jpa:
    show-sql: true
  flyway:
    locations: classpath:db/migration,classpath:db/dev

logging:
  level:
    com.smartiv: DEBUG
