import React, { useEffect, useState } from 'react';
import { api } from '../api.js';

/**
 * SMART MULTI-BED IV WORKFLOW & EVENT MONITORING PLATFORM
 * EventsPanel Component
 *
 * Displays:
 * - Event ID, Bed, Event Type, Start Time, End Time, Duration, Severity, Evidence Score, Status, Reason
 * - Filters: All Events, Bed 1, Bed 2
 * - Event details inspection modal
 */

export default function EventsPanel() {
  const [events, setEvents] = useState([]);
  const [filterBed, setFilterBed] = useState('ALL');
  const [selectedEvent, setSelectedEvent] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    let active = true;
    setLoading(true);

    const fetchPromise = filterBed === 'ALL'
      ? api.getCurrentEvents()
      : api.getBedEvents(filterBed);

    fetchPromise
      .then((data) => {
        if (active) {
          setEvents(data || []);
          setLoading(false);
        }
      })
      .catch((err) => {
        if (active) {
          setError(err.message || 'Failed to fetch events');
          setLoading(false);
        }
      });

    return () => {
      active = false;
    };
  }, [filterBed]);

  return (
    <div className="events-panel-container">
      {/* Header & Filter Controls */}
      <div className="panel-header-row">
        <div>
          <h2>IV Workflow Events</h2>
          <p className="panel-subtitle">
            Clinical event detection generated by backend rule engine & evidence scoring.
          </p>
        </div>

        <div className="filter-button-group">
          <button
            type="button"
            className={`btn-filter ${filterBed === 'ALL' ? 'active' : ''}`}
            onClick={() => setFilterBed('ALL')}
          >
            All Beds
          </button>
          <button
            type="button"
            className={`btn-filter ${filterBed === '1' ? 'active' : ''}`}
            onClick={() => setFilterBed('1')}
          >
            Bed 1
          </button>
          <button
            type="button"
            className={`btn-filter ${filterBed === '2' ? 'active' : ''}`}
            onClick={() => setFilterBed('2')}
          >
            Bed 2
          </button>
        </div>
      </div>

      {loading && <div className="loading-state">Loading events from API…</div>}
      {error && <div className="error-state">Error: {error}</div>}

      {!loading && !error && events.length === 0 && (
        <div className="empty-state">No events recorded for this selection.</div>
      )}

      {!loading && !error && events.length > 0 && (
        <div className="table-responsive">
          <table className="data-table events-table">
            <thead>
              <tr>
                <th>Event ID</th>
                <th>Bed</th>
                <th>Event Type</th>
                <th>Start Time</th>
                <th>Duration</th>
                <th>Severity</th>
                <th>Evidence Score</th>
                <th>Status</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {events.map((evt) => {
                const startTimeDisplay = evt.startTime
                  ? new Date(evt.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
                  : '—';

                return (
                  <tr key={evt.id} className={`event-row severity-${evt.severity.toLowerCase()}`}>
                    <td className="font-mono">{evt.id}</td>
                    <td>
                      <span className="bed-tag">Bed {evt.bedId}</span>
                    </td>
                    <td>
                      <strong>{evt.type}</strong>
                    </td>
                    <td>{startTimeDisplay}</td>
                    <td>{evt.duration}</td>
                    <td>
                      <span className={`pill-severity pill-${evt.severity.toLowerCase()}`}>
                        {evt.severity}
                      </span>
                    </td>
                    <td>
                      {evt.evidenceScore != null ? (
                        <span className="evidence-badge">
                          {(evt.evidenceScore * 100).toFixed(0)}%
                        </span>
                      ) : (
                        '—'
                      )}
                    </td>
                    <td>
                      <span className={`pill-status pill-${evt.status.toLowerCase()}`}>
                        {evt.status}
                      </span>
                    </td>
                    <td>
                      <button
                        type="button"
                        className="btn-link"
                        onClick={() => setSelectedEvent(evt)}
                      >
                        Details
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {/* Event Details Inspection Modal */}
      {selectedEvent && (
        <div className="modal-backdrop" onClick={() => setSelectedEvent(null)}>
          <div className="modal-content event-detail-modal" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h3>Event Details: {selectedEvent.id}</h3>
              <button className="btn-close" onClick={() => setSelectedEvent(null)}>✕</button>
            </div>
            <div className="modal-body">
              <div className="detail-grid">
                <div className="detail-item">
                  <label>Bed Identifier</label>
                  <span>Bed {selectedEvent.bedId}</span>
                </div>
                <div className="detail-item">
                  <label>Event Type</label>
                  <span className="text-strong">{selectedEvent.type}</span>
                </div>
                <div className="detail-item">
                  <label>Severity Level</label>
                  <span className={`pill-severity pill-${selectedEvent.severity.toLowerCase()}`}>
                    {selectedEvent.severity}
                  </span>
                </div>
                <div className="detail-item">
                  <label>Evidence Score</label>
                  <span>
                    {selectedEvent.evidenceScore != null
                      ? `${(selectedEvent.evidenceScore * 100).toFixed(1)}% (${selectedEvent.evidenceScore})`
                      : 'N/A'}
                  </span>
                </div>
                <div className="detail-item">
                  <label>Start Timestamp</label>
                  <span>{new Date(selectedEvent.startTime).toLocaleString()}</span>
                </div>
                <div className="detail-item">
                  <label>End Timestamp</label>
                  <span>{selectedEvent.endTime ? new Date(selectedEvent.endTime).toLocaleString() : 'Ongoing'}</span>
                </div>
              </div>

              <div className="detail-full-width">
                <label>Algorithmic Explanation / Root Cause</label>
                <div className="reason-callout">
                  {selectedEvent.reason}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
